version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: redux
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 1s
      timeout: 30s
      retries: 30
  setup:
    build:
      context: .
      dockerfile: Dockerfile-setup
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    command: "python create_DB.py"
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    command: "/usr/local/bin/gunicorn -b :8000 source.redux_API:api"
