version: '2'
services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: redux
  web:
    build:
      context: .
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: bash -c "./wait-for-it.sh redux_postgres_1:5432 -t 0 -- nose2"
